version: '3'
services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
  backend:
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=dbUser
      - DB_PASSWORD=dbPassword
  frontend:
    image: "front"
    ports:
      - 5000:5000
  redis:
    image: "redis:alpine"

