version: '3'
services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
  backend:
    image: "back"
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=dbUser
      - DB_PASSWORD=dbPassword
    depends_on:
      - db
  frontend:
    image: "front"
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost/api
  redis:
    image: "redis:alpine"
  nginx:
    image: "nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
