version: '3'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
  frontend:
    image: "front"
    ports:
      - 5000:5000
  redis:
    image: "redis:alpine"
